# Generated by Django 6.0.7 on 2026-07-24 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('no_of_dependents', models.IntegerField()),
                ('education', models.CharField(max_length=20)),
                ('self_employed', models.CharField(max_length=10)),
                ('income_annum', models.FloatField()),
                ('loan_amount', models.FloatField()),
                ('loan_term', models.IntegerField()),
                ('cibil_score', models.IntegerField()),
                ('residential_assets_value', models.FloatField()),
                ('commercial_assets_value', models.FloatField()),
                ('luxury_assets_value', models.FloatField()),
                ('bank_asset_value', models.FloatField()),
                ('prediction_result', models.CharField(blank=True, max_length=20)),
                ('prediction_probability', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_dependents', models.IntegerField()),
                ('education', models.CharField(choices=[('Graduate', 'Graduate'), ('Not Graduate', 'Not Graduate')], max_length=20)),
                ('self_employed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('income_annum', models.FloatField()),
                ('loan_amount', models.FloatField()),
                ('loan_term', models.IntegerField()),
                ('cibil_score', models.IntegerField()),
                ('residential_assets_value', models.FloatField()),
                ('commercial_assets_value', models.FloatField()),
                ('luxury_assets_value', models.FloatField()),
                ('bank_asset_value', models.FloatField()),
                ('loan_income_ratio', models.FloatField(default=0)),
                ('asset_loan_ratio', models.FloatField(default=0)),
                ('prediction_result', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20)),
                ('prediction_probability', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi')], default='en', max_length=10)),
                ('dark_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
